Sprint 06
KonstantinKirillOff/MovieQuiz-ios pull request #5
Opened 2022-11-19 14:46 UTC by KonstantinKirillOff

add fetching data from IMDB API

2022-11-20 11:27 UTC, ABashkirova requested changes

2022-11-20 11:27 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Обращу внимание на свойство `errorMessage`. 

Здесь может прийти текст с ошибкой, в таком случае сервис обычно возвращает пустой список фильмов `items`. С пустым списком приложение будет выглядеть сломанным. Это состояние называют краевым случаем, его стоит обрабатывать как ошибку, например, показывать алерт.
С точки зрения проектирования API сервиса IMDB, эту ошибку лучше вернуть c кодом ошибки клиента ([группа 4хх](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)). Но случается и так, что ответ имеет статус код 200, а тело ответа содержит сообщение об ошибке, как в нашем примере. Такой ответ в любом случае необходимо обработать разработчику фронтенда (web, iOS, android).

 **Примеры состояний, когда такое происходит:**

- API key неверный
- API key просрочен
- количество запросов в день превышено (по документации не больше 100)

2022-11-20 11:27 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        startActivityIndicator()
Здесь не очень важно, но принято сначала запускать лоадер, а потом ходить в сеть.

2022-11-20 11:27 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        if currentQuestionIndex ==  questionAmount - 1 {
```suggestion
        if currentQuestionIndex == questionAmount - 1 {
```

2022-11-20 11:27 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false
Рекомендую, использовать свойство [hidesWhenStopped](https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped) у activityIndicator вместо ручного управления isHidden

2022-11-20 11:27 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.show(quiz: quizStepViewModel)
Ты можешь дополнительно показывать activityIndicator между загрузкой вопросов, потому что после загрузки фильмов, загрузка постера тоже занимает некоторое время из-за получения изображения.

2022-11-20 11:27 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        12
а почему?

2022-11-20 11:27 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        moviesLoader.loadMovies { result in
Здесь не принципиально, не приводит к ошибке, однако правильнее поставить ослабление списка захвата на верхнем кложуре. 
```suggestion
        moviesLoader.loadMovies { [weak self] result in
```

2022-11-20 11:27 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                print(NetworkError.filedLoadImage.localizedDescription)
Нужно вернуть ошибку, как сказано в ТЗ:

> Если происходит ошибка загрузки, то показывается алерт с ошибкой.

2022-11-20 11:27 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +//                      rating: 8.1),
Удалим ненужный код?

2022-11-21 18:37 UTC, KonstantinKirillOff commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Очень крутой комментарий, спасибо! Зафиксировал себе, реализовал, но в своем решении сомневаюсь, похоже на костыль)

2022-11-21 18:39 UTC, KonstantinKirillOff commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        startActivityIndicator()
Изначально так и делал, потом решил все же, что преждевременно запускать индикатор, когда еще не идет загрузка, поправил!

2022-11-21 18:46 UTC, KonstantinKirillOff commented on MovieQuiz/Services/QuestionFactory.swift
> +        12
Тут решил сделать свойство для управления количеством вопросов, типа настройка) всего в выборке 250, этим свойством регулирую сколько хочу иметь в одной игре. Потом можно было бы сделать управление этим на уровне пользователя в настройках игры.

2022-11-21 19:17 UTC, KonstantinKirillOff commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.show(quiz: quizStepViewModel)
Старт поставил в момент нажатия кнопки да или нет, там ждем секунду, решил, что индикатор покажет, что все ок. Получается что он крутится секунду ожидания и получение картинки. И покрасил его в красный, так его хоть видно))

2022-11-21 19:20 UTC, KonstantinKirillOff commented on MovieQuiz/Services/QuestionFactory.swift
> +        moviesLoader.loadMovies { result in
Но и на нижнем тоже оставляем, правильно я понял?

2022-11-21 19:27 UTC, KonstantinKirillOff commented on MovieQuiz/Services/QuestionFactory.swift
> +                print(NetworkError.filedLoadImage.localizedDescription)
хм, на сколько помню в учебнике было через print именно

2022-11-21 19:28 UTC, KonstantinKirillOff commented on MovieQuiz/Services/QuestionFactory.swift
> +//                      rating: 8.1),
Тоже написано в учебнике, что нам это пригодится в будущем, специально не удалял

2022-11-21 19:28 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        startActivityIndicator()
тут такое: "потенциально" может случиться что код загрузки выполнится быстрее и выключит индикатор, раньше, чем ты его включишь

но такое произойдет, только если код будет последовательным

2022-11-21 19:34 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        12
Я рекомендую чтобы меньше вопросов у ревьювера было - пока поставить по ТЗ 10, а потом по своему желанию доделать :)

2022-11-21 19:35 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        moviesLoader.loadMovies { result in
Да, верно. Тут нюансики, описывать все случаи долго, я думаю уже можно ознакомиться с этой [статьей](https://habr.com/ru/company/otus/blog/666436/) и вернуться к ней через какое-то время еще раз :)

2022-11-21 20:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory = QuestionFactory.init(delegate: self, moviesLoader: MovieLoader())
:)
```suggestion
        questionFactory = QuestionFactory(delegate: self, moviesLoader: MovieLoader())
```

2022-11-21 20:16 UTC, ABashkirova commented on MovieQuiz/Services/MoviesLoader.swift
> +                        handler(.failure(NetworkError.serverError(mostPopularMovies.errorMessage)))
👍🏻

2022-11-21 20:16 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                print(NetworkError.filedLoadImage.localizedDescription)
Да, там слабый момент, соглашусь. Однако в случае с примером урока, там обрабатывается только строчка try Data. И в случае ошибки автор просто печатает текст ошибки в консоль, но при этом собирает ответ для пользователя без изображения. Даже если для пользователя это будет не очень и он не сможет верно без постера ответить на вопрос, в любом исходе - приложение не зайдет в тупик. 

Ты же взял блок больше, и если исключение будет вызвано на 97 строчке, то приложение просто напечатает текст и зайдет в тупик: нет места, где приложение перезапросит данные для этого вопроса или как-то поймет, что этот элемент нельзя отобразить (поправь, если это не так). 

Поэтому я посчитала этот вариант не просто слабым, но ошибочным :(  

Открыта к дискуссии здесь

2022-11-21 20:19 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>          }
В следующем спринте обязательно "логику разборка ошибки" нужно убрать из вьюконтроллела, тут лучше сразу максимально простые данные для отображения, чтобы лишнего ветвления не было

2022-11-22 05:45 UTC, ABashkirova approved these changes
Все хорошо! Текущие комментарии не критичны :)

2022-11-22 12:28 UTC, KonstantinKirillOff commented on MovieQuiz/Services/QuestionFactory.swift
> +                print(NetworkError.filedLoadImage.localizedDescription)
Пересмотрел еще раз, понял о чем ты говоришь, тут действительно из-за моей импровизации получится тупик. Спасибо, что указала на проблему)

2022-11-22 12:30 UTC, KonstantinKirillOff commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory = QuestionFactory.init(delegate: self, moviesLoader: MovieLoader())
ох, неужели это я написал так)? иногда сам удивляюсь, пошел исправлять))

2022-11-22 12:33 UTC, KonstantinKirillOff commented
add NetworkClient

2022-11-22 12:33 UTC, merged